eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
    service-url:
      default-zone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

spring:
  cloud:
    config:
      override-system-properties: false