spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: company-service
          uri: lb:http://COMPANY-SERVICE
          predicates:
            - Path=/api/companies/**
